const fs = require("fs");
const path = require("path");
const inquirer = require("inquirer");
const generateMarkdown = require("./utils/generateMarkdown");

// array of questions for user
const questions = [
  {
    type: "input",
    message: "What is your GitHub username?",
    name: "githubUsername",
  },
  {
    type: "input",
    message: "What is your email address?",
    name: "emailAddress",
  },
  {
    type: "input",
    message: "What is your project's name?",
    name: "projectName",
  },
  {
    type: "input",
    message: "Please write a short description of your project",
    name: "projectDescription",
  },
  {
    type: "list",
    message: "What kind of license should your project have?",
    name: "license",
    choices: ["MIT", "APACHE 2.0", "GPL 3.0", "BSD 3", "No license"], // update choices to show proper license types
  },
  {
    type: "input",
    message: "What command should be run to install dependencies?", // figure out how Dan only gave one option
    name: "installCommand",
  },
  {
    type: "input",
    message: "What command should be run to run tests?", // figure out how Dan only gave one option
    name: "testCommand",
  },
  {
    type: "input",
    message: "What does the user need to know about using the repo?",
    name: "howToUse",
  },
  {
    type: "input",
    message: "What does the user need to know about contributing to the repo?",
    name: "howToContribute",
  },
];

// function to write README file
// function writeToFile(fileName, data) {
//     fs.writeFile(`sampleREADME.md`, whatever is generated by generateMarkdown function, (err) =>
//         err ? console.error(err) :  console.log('Your professional README has been created!!')
//     )
// }

// function to initialize program
function init() {
  // use inquirer to take the user through the questions
  inquirer
    .prompt(questions)
    // then create variables to hold the user's responses
    .then((response) => {
      

      // console.log(githubUsername);
      // console.log(emailAddress);
      // console.log(projectName);
      // console.log(projectDescription);
      // console.log(license);
      // console.log(installCommand);
      // console.log(testCommand);
      // console.log(howToUse);
      // console.log(howToContribute);

      // maybe use the genrateMarkdown function to first populate the README with user's responses

      // then call the function to create a new file with the README text generated
      // writeToFile(fileName, data);

      fs.writeFileSync("sampleREADME.md",generateMarkdown(response))
    });
}

// function call to initialize program
init();
